language: node_js
node_js:
- '8'
branchs:
  only:
  - master
addons:
  ssh_known_hosts: 47.52.237.61
after_success:
- chmod 600 ~/.ssh/travis_rsa
- ssh root@real.breakinferno.cn -o StrictHostKeyChecking=no 'cd ~/work/blog && git
  pull && ./ci.bash'
before_install:
- openssl aes-256-cbc -K $encrypted_274299933b7c_key -iv $encrypted_274299933b7c_iv
  -in travis.enc -out travis -d
