language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_7ea6685e2a66_key -iv $encrypted_7ea6685e2a66_iv
  -in travis_rsa.enc -out ./travis_rsa -d
- chmod 777 ./ci.bash
- npm i -g npm
- openssl aes-256-cbc -K $encrypted_6094e4f462c1_key -iv $encrypted_6094e4f462c1_iv
  -in .travis/travis.enc -out ~/.ssh/id_rsa -d
addons:
    ssh_known_hosts: 47.52.237.61
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh root@real.breakinferno.cn -o StrictHostKeyChecking=no 'cd ~/work/blog && git
  pull & ./ci.bash'
