language: node_js
node_js:
- "node"
- "10"
- "9"
- "8"
cache: npm
before_install:
  - chomod 600 ./ci.bash
  - npm i -g npm
  - openssl aes-256-cbc -K $encrypted_6094e4f462c1_key -iv $encrypted_6094e4f462c1_iv -in .travis/travis.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh root@real.breakinferno.cn -o StrictHostKeyChecking=no 'cd ~/work/blog && git pull & ./ci.bash'
